import 'package:flutter/material.dart';

class RowDemo extends StatelessWidget {
  const RowDemo({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        mainAxisAlignment: MainAxisAlignment.end,
        crossAxisAlignment: CrossAxisAlignment.start,
        // mainAxisSize: ,
        children: const [
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),
          Text('ansh'),
          Text(' n.'),
          Text('chaniyara'),

        ],
      ),
    );
  }
}
